# Generated by Django 3.0.4 on 2020-03-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200325_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='asked_by',
        ),
    ]
