# Generated by Django 3.0.4 on 2020-03-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_asked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='asked_by',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
