# Generated by Django 3.0.4 on 2020-03-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200330_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='details',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='time',
        ),
        migrations.RemoveField(
            model_name='question',
            name='venue',
        ),
    ]
