# Generated by Django 3.0.4 on 2020-03-30 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0007_auto_20200331_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date_asked',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='details',
        ),
        migrations.AddField(
            model_name='question',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.TimeField(help_text='Please use the following format: <em>HH:MM:SS<em>', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='venue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
