# Generated by Django 3.0.4 on 2020-03-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20200331_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='detail',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=50),
        ),
    ]
