# Generated by Django 3.0.4 on 2020-03-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20200331_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='detail',
        ),
        migrations.AddField(
            model_name='question',
            name='aboutevent',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
