# Generated by Django 3.0.4 on 2020-04-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20200331_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
