# Generated by Django 3.0.4 on 2020-04-01 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0017_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='num_of_attendees',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
